name: CI

on:
  push:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: make dev-env
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: integration
        env:
          V3IO_API: ${{ secrets.V3IO_API }}
          V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
          V3IO_FRAMESD: ${{ secrets.V3IO_FRAMESD }}
        run: make integration
      - name: benchmark
        if: github.event_name != 'release'
        run: make bench
      - name: Store benchmark result
        if: github.event_name != 'release'
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: bench-results.json
          # Personal access token to deploy GitHub Pages branch
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
      - name: Build binary wheel and source tarball
        if: github.event_name == 'release'
        run: make dist
      - name: Publish package
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
